AWSTemplateFormatVersion: 2010-09-09
Description: >
  Load Balancer to distribute traffic between target in the app subnets

Parameters:
  ProjectName:
    Description: Specify the name of the project
    Type: String
    Default: mbti
  Environment:
    Description: Specify the environment in use
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - test
    - prod
  LBName:
    Description: Name of the Load Balancer to create
    Type: String
    Default: mbti-lb-server
  WorkflowId:
    Description: >
      An ID to uniquely identify each run of the template
      The Id will be use as part of the exported name for resources created or 
      for importing values where needed
    Type: String
    Default: de23469b-1ae3-4f4e-88e9-89a4d7e32a30

Resources:
  AppServerLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref LBName
      Type: application
      Scheme: internet-facing
      Subnets:
        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-AppSubnet1ID
        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-AppSubnet2ID
      SecurityGroups:
        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-LoadBalancerSG

  LBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref AppTargetGroup
      LoadBalancerArn: !Ref AppServerLB
      Port: 80
      Protocol: HTTP

  LBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref AppTargetGroup
      Conditions:
      - Field: path-pattern
        Values: [/]
      ListenerArn: !Ref LBListener
      Priority: 1

  AppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Port: 3005
      Protocol: HTTP
      UnhealthyThresholdCount: 10
      VpcId:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-VPC

Outputs:
  LoadBalancerARN:
    Description: ARN of the Load Balancer
    Value: !Ref AppServerLB
    Export:
      Name: !Sub ${ProjectName}-${Environment}-${WorkflowId}-LoadBalancerARN

  LoadBalancerDNS:
    Description: DNS of the Load Balancer
    Value: !GetAtt AppServerLB.DNSName
    Export:
      Name: !Sub ${ProjectName}-${Environment}-${WorkflowId}-LoadBalancerDNS

  LoadBalancerDNS2:
    Description: DNS of the Load Balancer
    Value: !Join ["", [http://, !GetAtt AppServerLB.DNSName]]
    Export:
      Name: !Sub ${ProjectName}-${Environment}-${WorkflowId}-LoadBalancerDNS2

  AppTargetGroupARN:
    Description: ARN of the app target group
    Value: !Ref AppTargetGroup
    Export:
      Name: !Sub ${ProjectName}-${Environment}-${WorkflowId}-AppTargetGroupARN
