AWSTemplateFormatVersion: 2010-09-09
Description: >
  Provision Postgres RDS Database

Parameters:
  ProjectName:
    Description: Specify the name of the project
    Type: String
    Default: mbti
  Environment:
    Description: Specify the environment in use
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
  DBInstanceClass:
    Description: Specify the capacity of the database instance
    Type: String
    Default: db.t2.micro
    AllowedValues:
      - db.t2.micro
      - db.t2.medium
  DBEngineVersion:
    Description: Database engine version to provision
    Type: String
    Default: "12.5"
    AllowedValues:
      - "12.5"
  AllocatedStorage:
    Description: Storage size for the database
    Type: String
    Default: 20
  DBName:
    Description: Name of the database to create
    Type: String
    Default: dcadatabase
  DBPort:
    Description: Database Port
    Type: Number
    Default: 5432
  DBMasterPassword:
    Description: >
      Password to connect to the Database.
      Should be provided dynamically.
      During execution
    Type: String
  DBMasterUsername:
    Description: Username for the database
    Type: String
    Default: dcadbuser
  SnapshotIdentifier:
    Description: Suffix for DB snapshot identifier
    Type: String
    Default: db-snapshot

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub ${ProjectName}-${Environment}-DBSubnetGroup
      DBSubnetGroupDescription: !Sub ${ProjectName}-${Environment} DB Subnet Group
      SubnetIds:
        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-DataSubnet1ID
        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-DataSubnet2ID
      # Tags:

  PrimaryRdsDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub ${ProjectName}-${Environment}-database
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: !Ref DBEngineVersion
      DBInstanceClass: !Ref DBInstanceClass
      AvailabilityZone:
        Fn::ImportValue: !Sub ${ProjectName}-${Environment}-DataSubnet1-AZ
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub ${ProjectName}-${Environment}-RDSDatabase-SGID 
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterPassword
      Port: !Ref DBPort
      MultiAZ: False
      PubliclyAccessible: False
      AllocatedStorage: !Ref AllocatedStorage
      DBSubnetGroupName: !Ref DBSubnetGroup

Outputs:
  DBInstanceName:
    Description: The name of the database instance
    Value: !Ref PrimaryRdsDatabase
    Export:
      Name: !Sub ${ProjectName}-${Environment}-DBInstanceName

  DBEndPoint:
    Description: Endpoint or hostname to connect to the database
    Value: !GetAtt PrimaryRdsDatabase.Endpoint.Address
    Export:
      Name: !Sub ${ProjectName}-${Environment}-DBHost

  DBPort:
    Description: Port number to connect to the databas
    Value: !GetAtt PrimaryRdsDatabase.Endpoint.Port

  DBSubnetGroupID:
    Description: ID of the RDS DB subnet group
    Value: !Ref DBSubnetGroup
    Export:
      Name: !Sub ${ProjectName}-${Environment}-DBSubnetGroupID

  DBSnapshotIdenfier:
    Description: Identifier for the db snapshot
    Value: !Sub ${ProjectName}-${Environment}-${SnapshotIdentifier}
    Export:
      Name: !Sub ${ProjectName}-${Environment}-SnapshotIdentifier
