version: 2.1

amazon_image: &amazon_image
  docker:
    - image: amazon/aws-cli
       
      environment:
        WORKFLOW_ID: $CIRCLE_WORKFLOW_ID

node_image: &node_image
  docker:
    - image: circleci/node:13.8.0

      environment:
        NODE_ENV: test
        TEST_DATABASE_URL: postgresql://root@localhost/circle_test
        WORKFLOW_ID: $CIRCLE_WORKFLOW_ID
    
    - image: circleci/postgres:9.6.5-alpine-ram

commands:
  configure_environment:
    steps:
      - run:
          name: Set workflow environment
          command: |
            export ENVIRONMENT=test
            # using develop for prod build
            if [[ $CIRCLE_BRANCH == develop ]]; then
              export ENVIRONMENT=prod
            fi

jobs:
  build:
    <<: *node_image

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            npm install

      - run:
          name: Run lint
          command: |
            npm run lint
  
  test:
    <<: *node_image

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Install Dependencies
          command: |
            env
            node server/createTable.js
            npm test
  
  provision_infrastructure:
    <<: *amazon_image

    steps:
      - checkout
      - configure_environment
      - run:
          name: Execute script to provision environment
          command: |
            cd aws-infra-cf
            . ./stack_helper.sh
            deploy_all   

workflows:
  default:
    jobs:
      - build
      - test:
          requires: [build]
