version: 2.1

default_image: &default_image
  docker:
    - image: amazon/aws-cli

node_image: &node_image
  docker:
    - image: circleci/node:13.8.0

      environment:
        NODE_ENV: test
        TEST_DATABASE_URL: postgresql://root@localhost/circle_test
    
    - image: circleci/postgres:9.6.5-alpine-ram

jobs:
  build:
    <<: *node_image

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            npm install

      - run:
          name: Run lint
          command: |
            npm run lint
  
  test:
    <<: *node_image

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Install Dependencies
          command: |
            env
            node server/createTable.js
            npm test
      

workflows:
  default:
    jobs:
      - build
      - test:
          requires: [build]
