version: 2.1

default_image: &default_image
  docker:
    - image: amazon/aws-cli

node_image: &node_image
   docker:
     - image: circleci/node:13.8.0

jobs:
  build:
    <<: *node_image

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            npm install

      - run:
          name: Run lint
          command: |
            npm run lint

workflows:
  default:
    jobs:
      - build
